version: '3.8'

services:
  dozzle:
    image: amir20/dozzle:latest
    restart: always             # run as a service    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./auth/data:/data
    ports:
      - 8888:8080
    environment:
      DOZZLE_ENABLE_ACTIONS: 1
      # DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_NO_ANALYTICS: 1
      DOZZLE_ENABLE_SHELL: 1
